// src/pages/home/index.vue
<template>
  <up-button
    type="primary"
    :text="model.test.value"
    @click="presenter.handleTestPinia"
    :customStyle="{
      marginBottom: '10px',
      marginTop: '10px',
    }"
  />
  <up-button
    type="primary"
    text="测试请求"
    @click="presenter.handleTestMock"
    :customStyle="{
      marginBottom: '10px',
    }"
  />

  <up-button
    type="primary"
    text="测试跳转about"
    @click="presenter.handleToAbout"
  />
</template>
<script lang="ts" setup>
import { usePresenter } from "./presenter";

const presenter = usePresenter();
const { model } = presenter;
</script>
<style lang="scss">
@import url("./index.scss");
</style>

// src/views/home/index.tsx
import "./index.less";

import { Button } from "antd";

import { usePresenter } from "./presenter";

export default () => {
  const presenter = usePresenter();
  const { model } = presenter;
  return (
    <>
      <div className="test">{model.test}</div>
      <Button onClick={presenter.handleToAbout}>测试跳转路由</Button>
    </>
  );
};
